### ISSUE TITLE
Passing in source maps and minified urls from environmental variables is failing/not working.

### ISSUE THREAD

**Issue by labithiotis** [rollbar/github-deploy-action#16]
I am trying to dynamically get all the source maps in my build folder and pass them to action. I have this job in my github action workflow:

```
  rollbar:
    name: Rollbar
    needs: [deploy_beta]
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: frontend/build/

      - name: Set source maps
        run: |
          echo ::set-env name=DATA_SOURCE_MAPS::$(find ./build/js/*.js.map | tr '\n' ' ')
          echo ::set-env name=DATA_SOURCE_MAPS_URLS::$(cd ./build && find ./js/*.js | tr '\n' ' ')

      - name: Rollbar deploy
        uses: rollbar/github-deploy-action@1.1.0
        with:
          environment: beta
          status: succeeded
          version: ${{ github.sha }}
          source_maps: ${{ env.DATA_SOURCE_MAPS }}
          minified_urls: ${{ env.DATA_SOURCE_MAPS_URLS }}
        env:
          ROLLBAR_USERNAME: ${{ github.actor }}
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
```

However this doesn't seem to be working as no source maps are uploaded. 

Do see this error:
```Warning: Unexpected input(s) 'source_maps', 'minified_urls', valid inputs are ['entryPoint', 'args', 'environment', 'version', 'status']```

Here's the full run command from github action log, i have shorted then source maps to make it more readable.

```Run rollbar/github-deploy-action@1.1.0
  with:
    environment: beta
    status: succeeded
    version: 0f0d76638489a1c38df17086f2f68ec1ffe4bd39
    source_maps: ./build/js/AuthCallback.3d04ac22dbeb5c6ad779.min.js.map ./build/js/commons.d980c7e5f06035544f82.min.js.map ./build/js/Conference.0e84c79a7af0c0942616.min.js.map ./build/js/Connect.a1f9b481f22c8b5fc5dc.min.js.map ./build/js/Explore.2da10a2098bac8d85fdb.min.js.map 
    minified_urls: ./js/AuthCallback.3d04ac22dbeb5c6ad779.min.js ./js/commons.d980c7e5f06035544f82.min.js ./js/Conference.0e84c79a7af0c0942616.min.js ./js/Connect.a1f9b481f22c8b5fc5dc.min.js ./js/Explore.2da10a2098bac8d85fdb.min.js 
  env:
    DATA_SOURCE_MAPS: ./build/js/AuthCallback.3d04ac22dbeb5c6ad779.min.js.map ./build/js/commons.d980c7e5f06035544f82.min.js.map ./build/js/Conference.0e84c79a7af0c0942616.min.js.map ./build/js/Connect.a1f9b481f22c8b5fc5dc.min.js.map ./build/js/Explore.2da10a2098bac8d85fdb.min.js.map 
    DATA_SOURCE_MAPS_URLS: ./js/AuthCallback.3d04ac22dbeb5c6ad779.min.js ./js/commons.d980c7e5f06035544f82.min.js ./js/Conference.0e84c79a7af0c0942616.min.js ./js/Connect.a1f9b481f22c8b5fc5dc.min.js ./js/Explore.2da10a2098bac8d85fdb.min.js
    ROLLBAR_USERNAME: labithiotis
    ROLLBAR_ACCESS_TOKEN: ***
/usr/bin/docker run --name e5c358ff4433fe8b64f09b40bf5c431d7cb57_510472 --label 1e5c35 --workdir /github/workspace --rm -e DATA_SOURCE_MAPS -e DATA_SOURCE_MAPS_URLS -e ROLLBAR_USERNAME -e ROLLBAR_ACCESS_TOKEN -e INPUT_ENVIRONMENT -e INPUT_STATUS -e INPUT_VERSION -e INPUT_SOURCE_MAPS -e INPUT_MINIFIED_URLS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/hablo/hablo":"/github/workspace" 1e5c35:8ff4433fe8b64f09b40bf5c431d7cb57  "beta" "0f0d76638489a1c38df17086f2f68ec1ffe4bd39" "succeeded"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   552  100    45  100   507     82    926 --:--:-- --:--:-- --:--:--  1010
```

**Comment by jackton1** [comment]
@labithiotis 

To resolve this you'll need to use


```yaml
...
    - name: Get Source maps and minified urls
      id: source-map-minified-urls
      run: |
        SOURCE_MAPS=$(ls -q | egrep '.js.map$' --exclude '.js$' | sort -u)
        while read LINE; do JS_MAPS="build/static/js/$LINE $JS_MAPS"; done << EOF
          $SOURCE_MAPS
        EOF
        SOURCE_FILES=$(ls -q | egrep '.js$' --exclude '.js.map$' | sort -u)
        while read LINE; do JS_ASSET="$STATIC_URL_PREFIX/$LINE $JS_ASSET"; done << EOF
          $SOURCE_FILES
        EOF
        echo "::set-output name=JS_MAPS::$JS_MAPS"
        echo "::set-output name=JS_ASSET::$JS_ASSET"
      env:
        STATIC_URL_PREFIX: '%PUBLIC_URL%'  ## This would be the URL where the assets are uploaded i.e GCS, CDN, HOSTNAME of your site  
      working-directory: build/static/js
    
    - name: Notify finish deploy to Rollbar
      uses: rollbar/github-deploy-action@2.0.0
      id: rollbar_post_deploy
      with:
        environment: 'staging'
        version: ${{ github.sha }}
        source_maps: ${{ steps.source-map-minified-urls.outputs.JS_MAPS }}
        minified_urls: ${{ steps.source-map-minified-urls.outputs.JS_ASSET }}
        status: 'succeeded'
      env:
        ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
        DEPLOY_ID: ${{ steps.rollbar_pre_deploy.outputs.deploy_id }}
        ROLLBAR_USERNAME: ${{ github.actor }}

```

**Comment by labithiotis** [comment]
@jackton1 Issue is, I was using older version of action. 

Update to rollbar/github-deploy-action@2.0.0 and using githubs new env syntaxt fixed it. 

```
      - name: Deploy Frontend
        run: ./run deploy:production
        working-directory: frontend

      - name: Set source maps
        id: source_maps
        working-directory: frontend
        run: |
          echo "DATA_SOURCE_MAPS=$(find ./build/js/*.js.map | tr '\n' ' ')" >> $GITHUB_ENV
          echo "DATA_SOURCE_MAPS_URLS=$(cd ./build && find ./js/*.js | sed -e 's/.\/js/\/\/myhablo.com\/js/' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Rollbar deploy
        uses: rollbar/github-deploy-action@2.0.0
        with:
          environment: production
          status: succeeded
          version: ${{ github.sha }}
          source_maps: ${{ steps.source_maps.env.DATA_SOURCE_MAPS }}
          minified_urls: ${{ steps.source_maps.env.DATA_SOURCE_MAPS_URLS }}
        env:
          ROLLBAR_USERNAME: ${{ github.actor }}
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
```
