### ISSUE TITLE
local_username doesnt work

### ISSUE THREAD

**Issue by webdesignberlin** [rollbar/github-deploy-action#20]
If i use local_username, i became the Annotations 1 warning:
`Unexpected input(s) 'local_username', valid inputs are ['entryPoint', 'args', 'environment', 'version', 'status', 'source_maps', 'minified_urls']`

Also the username are not display in rollbar.

my yml file:
```yml
# This is a basic workflow to help you get started with Actions

name: rollbar

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  rollbar:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Notify deploy to Rollbar
      uses: rollbar/github-deploy-action@2.0.0
      id: rollbar_deploy
      with:
        environment: 'production'
        version: ${{ github.sha }}
        local_username: ${{ github.actor }}
      env:
        ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
        # ROLLBAR_USERNAME:
```
