### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by introkun** [rollbar/github-deploy-action#30]
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

```
notify_rollbar:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Notify deploy to Rollbar
        uses: rollbar/github-deploy-action@2.1.1
```
